# ==========================================
# AEGIS OS - PACMAN CONFIGURATION
# ==========================================

[options]
HoldPkg           = pacman glibc
Architecture      = auto

# UI/UX Tweaks
Color
ILoveCandy
CheckSpace
VerbosePkgLists
ParallelDownloads = 8

# Security Signatures Enforcement
SigLevel          = Required DatabaseOptional
LocalFileSigLevel = Optional

# Core Repository
[core]
Include = /etc/pacman.d/mirrorlist

# Extra Repository (contains desktop environment, fonts, etc.)
[extra]
Include = /etc/pacman.d/mirrorlist

# Multilib Repository (CRITICAL: Required for 32-bit libraries for Wine/Windows apps compatibility)
[multilib]
Include = /etc/pacman.d/mirrorlist
